CREATE TABLE IF NOT EXISTS events (
  id SERIAL PRIMARY KEY,
  camera_id TEXT NOT NULL,
  ts TIMESTAMPTZ NOT NULL,
  label TEXT NOT NULL,
  confidence DOUBLE PRECISION NOT NULL,
  bbox DOUBLE PRECISION[] NOT NULL
);